export DATA_DIR=DREAM
CUDA_VISIBLE_DEVICES=0 python run_multiple_choice.py \
--do_lower_case \
--do_eval \
--do_test \
--do_train \
--overwrite_output \
--eval_all_checkpoints \
--task_name dream \
--per_gpu_eval_batch_size=8 \
--logging_steps 20 \
--max_seq_length 512 \
--model_type albert \
--model_name_or_path albert-base-v2 \
--data_dir $DATA_DIR \
--learning_rate 1e-5 \
--num_train_epochs 3 \
--output_dir albert_HRCAPlus \
--per_gpu_train_batch_size=4 \
--gradient_accumulation_steps 2 \
--warmup_steps 100 \
--save_steps 382